import React, { useState } from 'react';
import { BirthForm } from '../components/BirthForm';
import { calculatorService, type CalcInput } from '../services/api';
import { Sparkles, Loader } from 'lucide-react';

const inputStyle: React.CSSProperties = {
  width: '100%', background: 'rgba(255,255,255,0.04)', border: '1px solid var(--color-border-glass)',
  borderRadius: '8px', padding: '10px 14px', color: '#fff', fontSize: '0.9rem', outline: 'none', boxSizing: 'border-box',
};

export const AIInterpretation: React.FC = () => {
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [question, setQuestion] = useState('');
  const [input, setInput] = useState<CalcInput | null>(null);

  const handleFormSubmit = (d: CalcInput) => {
    setInput(d);
    submit(d, question);
  };

  const submit = async (d: CalcInput, q: string) => {
    setLoading(true); setError(''); setResult(null);
    try { setResult((await calculatorService.aiInterpret({ ...d, question: q })).data); }
    catch { setError('Interpretation failed. Please try again.'); }
    finally { setLoading(false); }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '32px' }}>
      <section style={{ textAlign: 'center' }}>
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
          <Sparkles size={32} color="var(--color-accent-gold)" />
          <h1 style={{ color: 'var(--color-accent-gold-light)', fontSize: '2rem' }}>AI Chart Reading</h1>
        </div>
        <p style={{ color: 'var(--color-text-muted)' }}>GPT-4 powered Vedic chart interpretation — personalised insights on personality, career, relationships, and life themes.</p>
      </section>

      <div className="cosmic-card" style={{ background: 'rgba(212,175,55,0.03)', border: '1px solid var(--color-border-gold)', padding: '14px 18px' }}>
        <p style={{ color: 'var(--color-text-muted)', fontSize: '0.82rem', margin: 0 }}>
          <strong style={{ color: 'var(--color-accent-gold)' }}>✨ AI-Powered:</strong> With an OpenAI API key configured, responses are generated by GPT-4o-mini. Without a key, you'll receive a detailed rule-based interpretation.
        </p>
      </div>

      <div className="cosmic-card">
        <label style={{ display: 'block', marginBottom: '6px', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>
          Your question for the AI (optional)
        </label>
        <input
          value={question}
          onChange={e => setQuestion(e.target.value)}
          placeholder="e.g. What are my career strengths? Will I marry soon? What is my life purpose?"
          style={inputStyle}
        />
      </div>

      <BirthForm title="Enter Birth Details" subtitle="The AI will analyse your complete chart and answer your question." onSubmit={handleFormSubmit} loading={loading} error={error} />

      {result && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div className="cosmic-card" style={{ border: '1px solid var(--color-border-gold)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
              <Sparkles size={20} color="var(--color-accent-gold)" />
              <h3 style={{ color: 'var(--color-accent-gold)', margin: 0 }}>
                {result.source === 'gpt-4o-mini' ? 'GPT-4 Vedic Reading' : 'Chart Interpretation'}
              </h3>
              <span style={{ marginLeft: 'auto', fontSize: '0.72rem', color: 'var(--color-text-muted)', background: 'rgba(255,255,255,0.05)', padding: '2px 8px', borderRadius: '10px' }}>{result.source}</span>
            </div>
            {result.interpretation.split('\n\n').map((para: string, i: number) => (
              <p key={i} style={{ color: 'var(--color-text-main)', lineHeight: '1.8', marginBottom: '14px', fontSize: '0.95rem' }}>{para}</p>
            ))}
          </div>

          {/* Ask follow-up */}
          {input && (
            <div className="cosmic-card" style={{ display: 'flex', gap: '10px' }}>
              <input
                value={question}
                onChange={e => setQuestion(e.target.value)}
                placeholder="Ask a follow-up question…"
                style={{ ...inputStyle, flex: 1 }}
                onKeyDown={e => e.key === 'Enter' && input && submit(input, question)}
              />
              <button
                onClick={() => input && submit(input, question)}
                disabled={loading}
                className="btn-gold"
                style={{ padding: '10px 18px', display: 'flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap' }}
              >
                {loading ? <Loader size={14} style={{ animation: 'spin 1s linear infinite' }} /> : <Sparkles size={14} />}
                Ask AI
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
